#!/bin/sh
ollama run gemma4 --hidethinking "Summarize (in French) this transcript cleanly into key takeaways, three sentences max, and you speak like caveman:\n\n$(python3 -m youtube_transcript_api $1 --format text --languages en fr)" 2>/dev/null
